apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd
  labels:
    example: basic
spec:
  nodePlacement:
    nodeSelector:
      kubernetes.io/os: CRX
  server:
    service:
      type: LoadBalancer
  redis:
      repository: harbor-wld.vcf.lab/niran/redis
      digest: sha256:6344a78bf6b62c2200ff873d7a3dde0b60db9b5a91c87b1efbc9130e1ac964d7