apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: argocd
  labels:
    example: basic
spec:
  nodePlacement:
    nodeSelector:
      kubernetes.io/os: CRX
  server:
    service:
      type: LoadBalancer
    redis:
      image: harbor-wld.vcf.lab/niran/redis:7.2.4