apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    argocd-attach: test
  name: niran-vks
  namespace: ns01
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.156.0/20
    serviceDomain: cluster.local
    services:
      cidrBlocks:
        - 10.96.0.0/12
  topology:
    class: builtin-generic-v3.3.0
    controlPlane:
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: os-image-id=vmi-008876b474d03887e
      replicas: 1
    variables:
      - name: vmClass
        value: best-effort-small
      - name: storageClass
        value: vsan-default-storage-policy
      - name: kubernetes
        value:
          security:
            podSecurityStandard:
              deactivated: true
          certificateRotation:
            enabled: true
            renewalDaysBeforeExpiry: 90
    version: v1.32.0---vmware.6-fips-vkr.2
    workers:
      machineDeployments:
        - class: node-pool
          metadata:
            annotations:
              run.tanzu.vmware.com/resolve-os-image: os-image-id=vmi-008876b474d03887e
          name: argo-example
          replicas: 1